defw:
    environment:
        DEFW_PATH: ${HOME}/ORNL/Quantum/QFw/defw
    parent-address: 127.0.0.1
    parent-port: 8090
    parent-name: resmgr
    name: resmgr
    shell: interactive
    type: resmgr
    path: ${DEFW_PATH}
    tmp: ${HOME}/tmp/resmgr
    loglevel: all

